format = """
 [\uE0B6[ $directory$git_branch$git_commit ](bold 14 inverted)\uE0B4](14) $rust $fill [\uE0B6[ $time ](white inverted)\uE0B4](white)
 [\uE0B6[ $shell$direnv ](green inverted)\uE0B4](green) $character 
"""

[fill]
symbol=" "

[time]
format="$time"
disabled = false

[shell]
format ='$indicator'
disabled = false
bash_indicator = "bash"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
format = "$symbol"
success_symbol = "[❯](bold green)"
error_symbol = "[](bold red)"

[directory]
truncate_to_repo = false
format = "[\uF07B $path ](bold cyan inverted)"

[git_branch]
symbol=""
format="[\uE0b1 $symbol $branch](bold cyan inverted)"

[git_commit]
commit_hash_length = 7
only_detached = false
tag_disabled = false
tag_symbol = " "
format="[  $hash$tag](bold 14 inverted)"

[direnv]
disabled = false
format = " \uE0b1 $symbol $allowed $loaded"
symbol = "env"
not_allowed_msg = "\uf057"
allowed_msg  = "\uf058"
loaded_msg = "󰇚"
unloaded_msg = "󱂰"


[rust]
symbol=""
format="[\uE0B6[$symbol ($version)](bold 9 inverted)\uE0B4](bold 9)"
